#!/usr/bin/env python3
"""
emit_spec.py — /upskill SOP step 5+6 (S6 slice)

Reads ranker output (S5) → picks top-1 (or all co-tied) → writes
~/.ship/upskill-<slug>/goals/01-spec.md + ledger entry to
~/inbox/_summaries/manual/upskill_<host>_<ts>.json.

The manual/ subdir is intentional — bigd panel reads only pending/<DATE>/
(see ~/.claude/skills/bigd/SKILL.md), so manual/ is path-invisible to bigd.

CLI:
  emit_spec.py --ranked RANKED.json [--top-n 1] [--no-write]

Exits 0 on success; 1 on parse / IO error.
"""
from __future__ import annotations

import argparse
import json
import platform
import socket
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

HKT = ZoneInfo("Asia/Hong_Kong")

LEDGER_DIR = Path.home() / "inbox" / "_summaries" / "manual"
SHIP_ROOT  = Path.home() / ".ship"


HANDOFF_BY_CAT = {
    "ADOPT-EXT":   ("extractskill", "/extractskill {url}"),
    "FIX-DRIFT":   ("ship continue", "/ship continue upskill-{slug}"),
    "FIX-PERF":    ("ship continue", "/ship continue upskill-{slug}"),
    "TRIM-SKILL":  ("ship continue", "/ship continue upskill-{slug}"),
    "CLEAN-HOUSE": ("ship continue", "/ship continue upskill-{slug}"),
}


def _host() -> str:
    h = socket.gethostname().lower()
    if "hel" in h:
        return "hel"
    if "london" in h or "vultr" in h:
        return "london"
    if platform.system().lower() == "darwin":
        return "mac"
    return h or "unknown"


def _spec_slug(cand: dict) -> str:
    cid = cand.get("id") or "anon"
    cat = (cand.get("ia_category") or "anon").lower()
    # id already includes a category-flavored prefix in most paths; normalize.
    slug = f"{cat}-{cid}".replace("--", "-").strip("-")
    return slug[:80]


def _proposed_action(cand: dict, slug: str) -> str:
    cat = cand.get("ia_category")
    if cat == "ADOPT-EXT":
        url = (cand.get("raw") or {}).get("url") or ""
        return f"/extractskill {url}".strip()
    return f"/ship continue upskill-{slug}"


def _handoff_target(cand: dict) -> str:
    cat = cand.get("ia_category", "")
    return HANDOFF_BY_CAT.get(cat, ("ship continue", ""))[0]


def _spec_body(cand: dict, slug: str, ts: str) -> str:
    cat   = cand.get("ia_category", "?")
    title = cand.get("title", "(no title)")
    src   = cand.get("source", "?")
    roi   = cand.get("roi", 0.0)
    imp   = cand.get("impact", 0)
    cost  = cand.get("expected_token_spend", 0)
    summ  = cand.get("summary") or "(no summary)"
    action = _proposed_action(cand, slug)
    handoff = _handoff_target(cand)

    return f"""# /upskill candidate: {title}

**Slug**: upskill-{slug}
**Date**: {ts}
**IA category**: [{cat}]
**Source**: {src}
**ROI**: {roi} (impact={imp}, expected_token_spend={cost})

## Why this surfaced

{summ}

## Proposed action

{action}

## Acceptance criteria

- Visible improvement in the metric flagged by the source ({src}).
- No regression in adjacent metrics (cache hit rate, dis_score, gap-severity counts).
- For ADOPT-EXT: skill installs cleanly and passes /skill-security-auditor.

## Hand-off target

{handoff}

---
Generated by /upskill {ts}. ROI is a SORT HINT not verdict — calibrate via Phase-2 --calibrate.
"""


def _write_spec(cand: dict, ts: str, no_write: bool) -> tuple[Path | None, str]:
    slug = _spec_slug(cand)
    path = SHIP_ROOT / f"upskill-{slug}" / "goals" / "01-spec.md"
    body = _spec_body(cand, slug, ts)
    if no_write:
        return None, slug
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path, slug


def _summarize(cand: dict) -> dict:
    return {
        "id":                   cand.get("id"),
        "ia_category":          cand.get("ia_category"),
        "source":               cand.get("source"),
        "title":                cand.get("title"),
        "impact":               cand.get("impact"),
        "expected_token_spend": cand.get("expected_token_spend"),
        "roi":                  cand.get("roi"),
        "co_tied":              cand.get("co_tied", False),
    }


def _write_ledger(ranked_doc: dict, spec_path: Path | None, ts_iso: str, host: str, no_write: bool) -> Path | None:
    LEDGER_DIR.mkdir(parents=True, exist_ok=True)
    ts_stamp = ts_iso.replace(":", "").replace("-", "").split(".")[0]
    path = LEDGER_DIR / f"upskill_{host}_{ts_stamp}.json"
    payload = {
        "ts":                   ts_iso,
        "host":                 host,
        "skill":                "upskill",
        "ranked":               [_summarize(c) for c in (ranked_doc.get("ranked") or [])[:5]],
        "spec_emitted":         str(spec_path) if spec_path else None,
        "co_tied_top":          ranked_doc.get("co_tied_top", False),
        "by_category":          ranked_doc.get("by_category", {}),
        "total_candidates":     ranked_doc.get("total_candidates", 0),
        "calibration_warning":  ranked_doc.get("calibration_warning"),
    }
    if no_write:
        return None
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False))
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description="/upskill spec emitter + ledger (S6)")
    ap.add_argument("--ranked",   required=True, help="Path to ranker output JSON")
    ap.add_argument("--top-n",    type=int, default=1)
    ap.add_argument("--no-write", action="store_true", help="Compute but don't write spec/ledger")
    args = ap.parse_args()

    ranked_path = Path(args.ranked)
    if not ranked_path.exists():
        print(f"[emit_spec] ERROR: ranked file not found: {ranked_path}", file=sys.stderr)
        return 1

    try:
        doc = json.loads(ranked_path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"[emit_spec] ERROR: parse {ranked_path}: {exc}", file=sys.stderr)
        return 1

    ranked = doc.get("ranked") or []
    if not ranked:
        print("[emit_spec] no candidates in ranked.ranked — nothing to emit", file=sys.stderr)
        # Still write a ledger row so the run is auditable.
        ts_iso = datetime.now(HKT).isoformat()
        host = _host()
        ledger_path = _write_ledger(doc, None, ts_iso, host, args.no_write)
        print(json.dumps({"spec": None, "ledger": str(ledger_path) if ledger_path else None, "candidates": 0}))
        return 0

    ts_iso = datetime.now(HKT).isoformat()
    host = _host()
    top = ranked[0]
    spec_path, slug = _write_spec(top, ts_iso, args.no_write)

    # Handle co-tied top: if both flagged, also write the second spec.
    extra_spec = None
    if doc.get("co_tied_top") and len(ranked) >= 2 and ranked[1].get("co_tied"):
        extra_spec, _ = _write_spec(ranked[1], ts_iso, args.no_write)

    ledger_path = _write_ledger(doc, spec_path, ts_iso, host, args.no_write)

    print(json.dumps({
        "spec":            str(spec_path) if spec_path else None,
        "spec_co_tied":    str(extra_spec) if extra_spec else None,
        "ledger":          str(ledger_path) if ledger_path else None,
        "slug":            slug,
        "ia_category":     top.get("ia_category"),
        "roi":             top.get("roi"),
        "co_tied_top":     doc.get("co_tied_top", False),
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
